include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

stages:
  - test
  - release

code_quality:
  artifacts:
    paths: 
      - gl-code-quality-report.json

dependency_scanning:
  artifacts:
    paths:
      - gl-dependency-scanning-report.json

license_scanning:
  artifacts:
    paths:
      - gl-license-scanning-report.json
    reports:
      license_scanning: gl-license-scanning-report.json

test-py27:
  stage: test
  image: themattrix/tox
  allow_failure: false
  script:
    - pip install --upgrade pip wheel setuptools
    - pip install tox
    - tox -e py27
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - cov-html-py27
      - coverage-py27.xml
      - junit-py27.xml
    reports:
      junit: junit-py27.xml

test-py36:
  stage: test
  image: themattrix/tox
  allow_failure: false
  script:
    - pip install --upgrade pip wheel setuptools
    - pip install tox
    - tox -e py36
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - cov-html-py36
      - coverage-py36.xml
      - junit-py36.xml
    reports:
      junit: junit-py36.xml

test-py37:
  stage: test
  image: themattrix/tox
  script:
    - pip install --upgrade pip wheel setuptools
    - pip install tox
    - tox -e py37
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - cov-html-py37
      - coverage-py37.xml
      - junit-py37.xml
    reports:
      junit: junit-py37.xml

test-py38:
  stage: test
  image: themattrix/tox
  allow_failure: false
  script:
    - pip install --upgrade pip wheel setuptools
    - pip install tox
    - tox -e py38
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - cov-html-py38
      - coverage-py38.xml
      - junit-py38.xml
    reports:
      junit: junit-py38.xml

release-test-pypi-py2:
  stage: release
  image: python:2.7-slim
  variables:
    TWINE_USERNAME: $TEST_PYPI_USERNAME
    TWINE_PASSWORD: $TEST_PYPI_PASSWORD
  script:
    - pip install -U twine wheel setuptools
    - python setup.py bdist_wheel
    - twine check dist/*
    - twine upload --repository-url $TEST_PYPI_URL dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

release-pypi-py2:
  stage: release
  image: python:2.7-slim
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install -U twine wheel setuptools
    - python setup.py bdist_wheel
    - twine check dist/*
    - twine upload dist/*
  rules:
    - if: $CI_COMMIT_TAG

release-test-pypi-py3:
  stage: release
  image: python:3.7-slim
  variables:
    TWINE_USERNAME: $TEST_PYPI_USERNAME
    TWINE_PASSWORD: $TEST_PYPI_PASSWORD
  script:
    - pip install -U twine wheel setuptools
    - python setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload --repository-url $TEST_PYPI_URL dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

release-pypi-py3:
  stage: release
  image: python:3.7-slim
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install -U twine wheel setuptools
    - python setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload dist/*
  rules:
    - if: $CI_COMMIT_TAG
