# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .